### ISSUE TITLE
Create CLI modules

### ISSUE THREAD

**Issue by kaanyagci** [Makepad-fr/scraping.house#28]
Convert the current CLI structure to a modular structure. 

For each topic (`linked`, `insta`, `fb` and `screenshot`) we want to create a plugin that will be installed by the user in production.

## TODOs:

- [ ] Create `plugins` directory and update rush configuration
- [ ] Create plugins with `oclif` CLI
- [ ] Move all related code (source and tests) to each plugin directory
- [ ] Publish all plugins on npm with `@scraping.house/cli-<plugin_name>-plugin` convention
- [ ] Update documentation page of CLI
