### ISSUE TITLE
Get skills & endorsements from user profile

### ISSUE THREAD

**Issue by kaanyagci** [Makepad-fr/scraping.house#31]
From LinkedIn user profile we want to get skills & endorsement information.

## TODOs

- [ ] Check if the section present on the user profile
- [ ] Expand the section to access all items
- [ ] For each category get (skill, hasAssesmentBadge, numberOfEndorsements)
- [ ] Add related changes to the CLI `linked:profile` command
