### ISSUE TITLE
Get interests from user profile

### ISSUE THREAD

**Issue by kaanyagci** [Makepad-fr/scraping.house#32]
From the LinkedIn user profile, we want to get interests section information

## TODOs:

- [ ] Check if the section present on the user's profile
- [ ] Click on "see all" button to get the pop-up
- [ ] Get tabs of the pop-up window
- [ ] For each tab, scroll and get name, link of the element
- [ ] Update CLI `linked:profile` command following the changes
