### ISSUE TITLE
Get accomplishments of the user 

### ISSUE THREAD

**Issue by kaanyagci** [Makepad-fr/scraping.house#33]
Get accomplishments from the user's LinkedIn profile. 

## TODOs:

- [ ] Verify if the section is present in the user profile
- [ ] Expand each sub-section
- [ ] Get each items title, dates, and description
- [ ] Update CLI `linked:profile` command following model changes
