### ISSUE TITLE
Create company module

### ISSUE THREAD

**Issue by kaanyagci** [Makepad-fr/scraping.house#36]
We want to create a company module to get information from the company's LinkedIn page.

## TODOs:

- [ ] Get base information from the company's page
- [ ] Get people to list from the company's page
- [ ] Get job announcements from the company's page
- [ ] Get posts from company's page
- [ ] Create  `linked:company` command on CLI
